// <auto-generated />
using System;
using GeomidisSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeomidisSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231026031223_InitialMigration3")]
    partial class InitialMigration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeomidisSystem.Models.PaisExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CANBEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CANBEN2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CANBEN3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CANBEN4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CANBEN5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("paisExamples");
                });

            modelBuilder.Entity("GeomidisSystem.Models.SpgPsCaratamb", b =>
                {
                    b.Property<string>("CODTAM")
                        .HasColumnType("text");

                    b.Property<int?>("ALTITU")
                        .HasColumnType("integer");

                    b.Property<int?>("AREA")
                        .HasColumnType("integer");

                    b.Property<int?>("CANPOB")
                        .HasColumnType("integer");

                    b.Property<int?>("CANVIV")
                        .HasColumnType("integer");

                    b.Property<float?>("CENPOB")
                        .HasColumnType("real");

                    b.Property<float?>("COUBIX")
                        .HasColumnType("real");

                    b.Property<float?>("COUBIY")
                        .HasColumnType("real");

                    b.Property<string>("COUNTE")
                        .HasColumnType("text");

                    b.Property<string>("CUENCA")
                        .HasColumnType("text");

                    b.Property<string>("DEPART")
                        .HasColumnType("text");

                    b.Property<string>("DISTRI")
                        .HasColumnType("text");

                    b.Property<string>("EJETEM")
                        .HasColumnType("text");

                    b.Property<string>("ESTADO")
                        .HasColumnType("text");

                    b.Property<int?>("HOGARE")
                        .HasColumnType("integer");

                    b.Property<Point>("IDEASG")
                        .HasColumnType("geometry");

                    b.Property<string>("IMPEST")
                        .HasColumnType("text");

                    b.Property<int?>("NCPAIN")
                        .HasColumnType("integer");

                    b.Property<string>("NOMTAM")
                        .HasColumnType("text");

                    b.Property<int?>("NUMATEN")
                        .HasColumnType("integer");

                    b.Property<int?>("NUMINT")
                        .HasColumnType("integer");

                    b.Property<int?>("NUMUSU")
                        .HasColumnType("integer");

                    b.Property<int?>("PERIME")
                        .HasColumnType("integer");

                    b.Property<int?>("POBOBJ")
                        .HasColumnType("integer");

                    b.Property<string>("PROVIN")
                        .HasColumnType("text");

                    b.Property<string>("SNIPTA")
                        .HasColumnType("text");

                    b.Property<string>("TIPINT")
                        .HasColumnType("text");

                    b.Property<string>("UBIGEO")
                        .HasColumnType("text");

                    b.Property<string>("ZOPOTE")
                        .HasColumnType("text");

                    b.HasKey("CODTAM");

                    b.ToTable("spgPsCaratambs");
                });

            modelBuilder.Entity("GeomidisSystem.Models.SpgPsGeometry", b =>
                {
                    b.Property<string>("CODTAM")
                        .HasColumnType("text");

                    b.Property<Geometry>("IDEASG")
                        .HasColumnType("geometry");

                    b.Property<string>("NOMTAM")
                        .HasColumnType("text");

                    b.Property<string>("UBIGEO")
                        .HasColumnType("text");

                    b.HasKey("CODTAM");

                    b.ToTable("spgPsGeoemtrys");
                });
#pragma warning restore 612, 618
        }
    }
}
