// <auto-generated />
using GeomidisSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeomidisSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeomidisSystem.Models.PaisExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CANBEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CANBEN2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CANBEN3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CANBEN4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CANBEN5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("paisExamples");
                });
#pragma warning restore 612, 618
        }
    }
}
